[phases.setup]
nixPkgs = ['python311', 'pip']

[phases.install]
cmds = [
    'python -m pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[start]
cmd = 'uvicorn server:app --host 0.0.0.0 --port $PORT'